### PR TITLE
 Upgrade to latest for wgpu

### PR DESCRIPTION
**Pull request by Dispersia**
Draft PR: If preferred to not have hanging PR's feel free to close, just to show work that has been done if others want to try and test with it.

  On working on the android stuff for iced, moves to wgsl to remove shader-c (for iced specifically, to sync wgpu versions), so just updates wgpu on this crate so I can work on latest wgpu on iced.

Closes #63.
Closes #67.

### CODE REVIEW

**Comment by adamnemecek** [comment]
Holy fuck, I literally opened a PR for this, not realizing you did too.

**Comment by Dispersia** [comment]
haha, unfortunate timing. I have it for iced as well, however there seems to be a bug in stagingbelt not resetting offset that I'm looking into now: https://github.com/Dispersia/iced/tree/upgrade-wgpu . I'm still learning wgpu-rs so if you have more insight would be useful :)

**Comment by adamnemecek** [comment]
Yeah, like what are the odds. On the same day. 

You might be interested in this project I’m invovled with, femtovg. https://github.com/adamnemecek/femtovg Its a 2d graphics API. I recently added a wgpu backend. Join the discord while at it!

**Comment by Dispersia** [comment]
updated to 0.8, should be ready for review

**Pull request merged**
