### PR TITLE
Switched to Queue based rendering

### PR DESCRIPTION
**Pull request by genusistimelord**
So based on #69 I have updated this to use the latest version and have Temporarily fixed the Scissoring issue.

The issue seems to be the Command buffer if using staging belt would be copy draw copy draw while with queue would be copy copy copy draw draw draw.  So Until you decide to change the way the system buffers the rendering into a single Draw call that holds onto index's in a uniform array or something else we will be forced to use Fragment Shader scissoring. 

When switching to use queue over the staging belt we gain the benefit of being able to render with Tokio async on Main with winit Event loop.

Also the Clipper is not the Greatest as it is Actual Screen coords so the best way to improve upon this would probably be to calculate offsets into the Region before passing it onto the GPU.

### CODE REVIEW

**Comment by genusistimelord** [comment]
this does fix the region scissor issue.

image

**Comment by profan** [comment]
Hah, nice way to handle it 👀 Glad someone else got it in! I do wonder what the impact of the fragment shader based discard might be, but maybe it's alright

**Comment by genusistimelord** [comment]
> Hah, nice way to handle it 👀 Glad someone else got it in!
> 
> I do wonder what the impact of the fragment shader based discard might be, but maybe it's alright

there should not be much impact since the GPU should optimize the rendering based on that. Though if we figured out a way to stream render glyphs which would mean to render an entire string in the shader versus inserting the string into a texture. we could still use the other method of clipping then.

**Comment by genusistimelord** [comment]
just updated this so it is now inline with master. Sadly had to do this the hard way since git did not want to auto merge =[.

**Comment by pimlu** [comment]
Hey, thank you for making this PR, I was having similar issues as #78 except in other browsers, and this PR fixed it (as people suspected, it was some kind of caching thing). I made a small extra modification [here](https://github.com/genusistimelord/wgpu_glyph/pull/3) that made the API work better with my app.

**Comment by genusistimelord** [comment]
I have updated this which fixes the scissor and rendering issues that it originally had. it works without the staging belt! @hecrj

**Comment by VincentJousse** [comment]
@hecrj will this be merged anytime soon ?

**Pull request closed without merging**
