### PR TITLE
Use Queue instead of StagingBelt for buffer/texture writes.

### PR DESCRIPTION
**Pull request by profan**
I was having a situation where StagingBelt was leaking a tremendous amount of memory (like 10MB/second given my use of wgpu_glyph, so I took the liberty of swapping out StagingBelt use for Queue), it seems you may already have had the same idea given the comment inside cache.rs?

I also fixed my issue with the cache being corrupted (it was me leaving in half the buffer use that wasn't necessary anymore, order of writes to queue vs encoder use wasn't what I expected), the only thing which might be a little weird is the now local Vec kept in cache.rs to hold the padded data and the use of unsafe there for set_len, but here it is anyways, ready for review 👀

### CODE REVIEW

**Comment by Mubelotix** [comment]
This is a great idea but aren't StagingBelt supposed to be more efficient? Did you open an issue?

**Comment by profan** [comment]
> 
> 
> This is a great idea but aren't StagingBelt supposed to be more efficient? Did you open an issue?

StagingBelt currently leaks a dramatic amount of memory and from what I've heard from some of the people working on wgpu-rs side things, it seems while it technically does avoid a copy, it's easier API-side to "do the right" thing apparently efficiency wise if you just use queue's write_buffer directly?

**Review by hecrj — COMMENTED** [review]
The main issue with using `Queue::write_buffer` is that we lose composability.

With a `StagingBelt`, writes are recorded in the `CommandEncoder`. With a `Queue`, writes are global and happen all at once during `submit`. This means that the buffers will be overwritten and only contain the data of the last `draw_queued` call.

For instance, the `clipping` example is most likely broken here.

**Comment by profan** [comment]
> 
> 
> The main issue with using `Queue::write_buffer` is that we lose composability.
> 
> With a `StagingBelt`, writes are recorded in the `CommandEncoder`. With a `Queue`, writes are global and happen all at once during `submit`. This means that the buffers will be overwritten and only contain the data of the last `draw_queued` call.
> 
> For instance, the `clipping` example is most likely broken here.

Oh yeah, you're right, the expected ordering does fall apart basically, oof.

Hmm, maybe fixing StagingBelt is the easier solution in this case then actually...

**Comment by schell** [comment]
Just a note because I just figured this out - since these changes now use `Queue::write_texture`, padding the data to multiples of COPY_BYTES_PER_ROW_ALIGNMENT is not necessary and so `padded_cache` can disappear. 

https://docs.rs/wgpu/0.9.0/wgpu/constant.COPY_BYTES_PER_ROW_ALIGNMENT.html

**Comment by profan** [comment]
> 
> 
> Just a note because I just figured this out - since these changes now use `Queue::write_texture`, padding the data to multiples of COPY_BYTES_PER_ROW_ALIGNMENT is not necessary and so `padded_cache` can disappear.
> 
> https://docs.rs/wgpu/0.9.0/wgpu/constant.COPY_BYTES_PER_ROW_ALIGNMENT.html

Good catch, changed it, simplifies things a bit, things are still bent as write_texture/write_buffer don't compose the same way the queued encoder operations do, but I might have a stab at making that work some time soon to make stagingbelt unnecessary

**Comment by hecrj** [comment]
Closing in favor of #76.

**Pull request closed without merging**
